<a href="https://colab.research.google.com/github/Rzarcik97/FilmLyApp/blob/main/A_B_test___1__Filmly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

All information about the test is through this [link](https://docs.google.com/document/d/1kLHXTwNTYzmxNONggCKdnSXuuwP55QV-9mN5M7ka9o8/edit?tab=t.0).

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/Mate_HW

/content/drive/MyDrive/Mate_HW

In [3]:
test = pd.read_excel('ab_test_synthetic_dataset.xlsx')

In [4]:
test.head()

,user_id,session_date,day_of_week,variant,traffic_source,device_type,country,non_registered_user,cta_clicked,signup_completed,recommendation_cards_clicked,bounced,session_duration_seconds
0,100001,2026-04-11,Sat,A,organic,mobile,US,1,0,0,0,1,11
1,100002,2026-04-11,Sat,A,referral,mobile,US,1,0,0,0,1,21
2,100003,2026-04-11,Sat,A,referral,mobile,US,1,0,0,0,1,23
3,100004,2026-04-11,Sat,A,organic,mobile,US,1,0,0,0,0,73
4,100005,2026-04-11,Sat,A,direct,mobile,US,1,0,0,0,1,14

In [5]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   user_id                       700 non-null    int64
 1   session_date                  700 non-null    datetime64[ns]
 2   day_of_week                   700 non-null    object
 3   variant                       700 non-null    object
 4   traffic_source                700 non-null    object
 5   device_type                   700 non-null    object
 6   country                       700 non-null    object
 7   non_registered_user           700 non-null    int64
 8   cta_clicked                   700 non-null    int64
 9   signup_completed              700 non-null    int64
 10  recommendation_cards_clicked  700 non-null    int64
 11  bounced                       700 non-null    int64
 12  session_duration_seconds      700 non-null    int64
dtypes: datetime64[ns](1), int64(7), object(5)
memory usage: 71.2+ KB

In [6]:
test['user_id'].nunique()

700

In [7]:
test_1 = test.groupby('variant').agg({
    'user_id': 'nunique',
    'cta_clicked': 'sum',
    'signup_completed': 'sum',
    'recommendation_cards_clicked': 'sum',
    'bounced': 'sum'
})
print(test_1)

         user_id  cta_clicked  signup_completed  recommendation_cards_clicked  \
variant
A            350           21                 7                             0
B            350           32                15                            64

         bounced
variant
A            244
B            197

In [8]:
test_perc = round(test.groupby('variant').agg({
    'user_id': 'nunique',
    'cta_clicked': 'sum',
    'signup_completed': 'sum',
    'recommendation_cards_clicked': 'sum',
    'bounced': 'sum'
}) * 100 / (test.shape[0]/2),2)

test_perc

,user_id,cta_clicked,signup_completed,recommendation_cards_clicked,bounced
variant,,,,,
A,100.0,6.00,2.00,0.00,69.71
B,100.0,9.14,4.29,18.29,56.29

In [9]:
z_stat, p_value = sm.stats.proportions_ztest(test_1['cta_clicked'], test_1['user_id'])

print(f'CTA_clicked results:')
print("\nZ-statistic:", z_stat)
print("P-value:", p_value)
if p_value > 0.05:
         print('Results are not statistically significant.')
else:
         print(' Results are statistically significant.')

print(f'Absolute difference: {abs(test_1['cta_clicked'].iloc[0] - test_1['cta_clicked'].iloc[1])} , {round(abs(test_perc['cta_clicked'].iloc[0] -  test_perc['cta_clicked'].iloc[1]),2)}%')
print(f'Relative difference: {round((test_perc['cta_clicked'].iloc[1] - test_perc['cta_clicked'].iloc[0]) * 100 / test_perc['cta_clicked'].iloc[0],2)} %')

CTA_clicked results:

Z-statistic: -1.5716347761073892
P-value: 0.11603527651786896
Results are not statistically significant.
Absolute difference: 11 , 3.14%
Relative difference: 52.33 %

In [10]:
z_stat, p_value = sm.stats.proportions_ztest(test_1['signup_completed'], test_1['user_id'])

print(f'Signup Rate results:')
print("\nZ-statistic:", z_stat)
print("P-value:", p_value)
if p_value > 0.05:
         print('Results are not statistically significant.')
else:
         print(' Results are statistically significant.')


print(f'Absolute difference: {abs(test_1['signup_completed'].iloc[0] - test_1['signup_completed'].iloc[1])} , {round(abs(test_perc['signup_completed'].iloc[0] -  test_perc['signup_completed'].iloc[1]),2)}%')
print(f'Relative difference: {round((test_perc['signup_completed'].iloc[1] - test_perc['signup_completed'].iloc[0]) * 100 / test_perc['signup_completed'].iloc[0],2)} %')

Signup Rate results:

Z-statistic: -1.733056891543638
P-value: 0.08308555741251715
Results are not statistically significant.
Absolute difference: 8 , 2.29%
Relative difference: 114.5 %

In [11]:
z_stat, p_value = sm.stats.proportions_ztest(test_1['bounced'], test_1['user_id'])

print(f'Bounced Rate results:')
print("\nZ-statistic:", z_stat)
print("P-value:", p_value)
if p_value > 0.05:
         print('Results are not statistically significant.')
else:
         print(' Results are statistically significant.')


print(f'Absolute difference: {abs(test_1['bounced'].iloc[0] - test_1['bounced'].iloc[1])} , {round(abs(test_perc['bounced'].iloc[0] -  test_perc['bounced'].iloc[1]),2)}%')
print(f'Relative difference: {round((test_perc['bounced'].iloc[1] - test_perc['bounced'].iloc[0]) * 100 / test_perc['bounced'].iloc[0],2)} %')

Bounced Rate results:

Z-statistic: 3.679405906357998
P-value: 0.0002337779236601471
 Results are statistically significant.
Absolute difference: 47 , 13.42%
Relative difference: -19.25 %

Despite positive changes in metrics, most results are not statistically significant because sample groups are not large enough to support a 3% lift instead of a 5% one.
However, there is positive dynamics. Therefore, it is recommended to continutue gathering data. To detect 3% uplift in CTA rate the test should be run for 10 days more.